sudo: false
language: python
cache: pip
python:
  - "3.6"
env:
  - BASEDIR="https://raw.githubusercontent.com/open-contracting/standard-maintenance-scripts/master"
install:
  - curl -s -S $BASEDIR/tests/install.sh | bash -
script:
  - curl -s -S $BASEDIR/tests/script.sh | bash -
  - python -m unittest discover
